server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://localhost:5432/postgres
    url: jdbc:postgresql://queenie.db.elephantsql.com:5432/fcneplvd
    #username: postgres
    username: fcneplvd
    #password: 123456
    password: PZgIQdzGVRayvY3mHYRvhF5gKmSLhB6H
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander
  version: 1.0.0